# CMake generated Testfile for 
# Source directory: C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests
# Build directory: C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[all_plugins_smoke_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/all_plugins_smoke_test.exe")
set_tests_properties([=[all_plugins_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[auto_frame_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/auto_frame_test.exe")
set_tests_properties([=[auto_frame_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[baseline_regression_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/baseline_regression_test.exe")
set_tests_properties([=[baseline_regression_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[bezier_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/bezier_test.exe")
set_tests_properties([=[bezier_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[builtin_gradients_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/builtin_gradients_test.exe")
set_tests_properties([=[builtin_gradients_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[core_smoke_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/core_smoke_test.exe")
set_tests_properties([=[core_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[flame_clone_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/flame_clone_test.exe")
set_tests_properties([=[flame_clone_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[flame_io_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/flame_io_test.exe")
set_tests_properties([=[flame_io_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[flame_ops_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/flame_ops_test.exe")
set_tests_properties([=[flame_ops_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[gpu_baseline_parity_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/gpu_baseline_parity_test.exe")
set_tests_properties([=[gpu_baseline_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[gpu_progress_control_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/gpu_progress_control_test.exe")
set_tests_properties([=[gpu_progress_control_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[gpu_variation_parity_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/gpu_variation_parity_test.exe")
set_tests_properties([=[gpu_variation_parity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[gradient_io_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/gradient_io_test.exe")
set_tests_properties([=[gradient_io_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[gradient_ops_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/gradient_ops_test.exe")
set_tests_properties([=[gradient_ops_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[mutation_ops_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/mutation_ops_test.exe")
set_tests_properties([=[mutation_ops_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[plugin_variations_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/plugin_variations_test.exe")
set_tests_properties([=[plugin_variations_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[png_writer_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/png_writer_test.exe")
set_tests_properties([=[png_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[random_flame_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/random_flame_test.exe")
set_tests_properties([=[random_flame_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[renderer_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/renderer_test.exe")
set_tests_properties([=[renderer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[scratch_user_roundtrip_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/scratch_user_roundtrip_test.exe")
set_tests_properties([=[scratch_user_roundtrip_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[smooth_palette_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/smooth_palette_test.exe")
set_tests_properties([=[smooth_palette_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[symmetry_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/symmetry_test.exe")
set_tests_properties([=[symmetry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[triangle_geometry_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/triangle_geometry_test.exe")
set_tests_properties([=[triangle_geometry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[variation_roundtrip_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/variation_roundtrip_test.exe")
set_tests_properties([=[variation_roundtrip_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[variations_batch1_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/variations_batch1_test.exe")
set_tests_properties([=[variations_batch1_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[variations_batch2_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/variations_batch2_test.exe")
set_tests_properties([=[variations_batch2_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[variations_batch3_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/variations_batch3_test.exe")
set_tests_properties([=[variations_batch3_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[variations_batch4_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/variations_batch4_test.exe")
set_tests_properties([=[variations_batch4_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[variations_batch5_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/variations_batch5_test.exe")
set_tests_properties([=[variations_batch5_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[variations_batch6_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/variations_batch6_test.exe")
set_tests_properties([=[variations_batch6_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
add_test([=[variations_batch7_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/variations_batch7_test.exe")
set_tests_properties([=[variations_batch7_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/CMakeLists.txt;0;")
subdirs("ui")
