#pragma once

// Generated by CMake (src/ui/CMakeLists.txt's configure_file() call) from
// APO_VERSION (top-level CMakeLists.txt) - the same single source of truth
// used for package filenames/bundle metadata (cmake/Packaging.cmake) and
// the release.yml tag this must match for UpdateChecker's version
// comparison to mean anything. Not committed (generated into the build
// directory, like every other CMake-configured file here) - see
// AppVersion.h.in's own path for the template this comes from.

namespace apo::ui {
constexpr const char* kAppVersion = "1.0.0";
} // namespace apo::ui
