#pragma once

#include "ColorMap.h"

namespace apo {

// The ~701 built-in flam3-style gradients from the original's ColorMap/
// cmapdata.pas (e.g. "south-sea-bather", "sky-flesh", ...) - a gap
// explicitly flagged in ColorMap.h's parseGradientString() doc comment as
// "not hand-ported; a follow-up generation script should translate that
// file mechanically". BuiltinGradients.cpp is exactly that: mechanically
// generated by scripts/generate_builtin_gradients.py, not hand-written -
// see that script's own header comment. Lets GradientBrowserDialog offer a
// curated palette library out of the box, with no external .ugr/.map file
// needed.
int builtinGradientCount();

// Index must be in [0, builtinGradientCount()) - matches cmapdata.pas's
// CMapNames, e.g. "000_south-sea-bather".
const char* builtinGradientName(int index);
ColorMap builtinGradient(int index);

} // namespace apo
