# CMake generated Testfile for 
# Source directory: C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui
# Build directory: C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[triangle_canvas_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/triangle_canvas_interaction_test.exe")
set_tests_properties([=[triangle_canvas_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;10;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[adjust_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/adjust_dialog_interaction_test.exe")
set_tests_properties([=[adjust_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;14;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[render_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/render_dialog_interaction_test.exe")
set_tests_properties([=[render_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;18;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[options_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/options_dialog_interaction_test.exe")
set_tests_properties([=[options_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;22;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[mutate_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/mutate_dialog_interaction_test.exe")
set_tests_properties([=[mutate_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;26;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[gradient_browser_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/gradient_browser_dialog_interaction_test.exe")
set_tests_properties([=[gradient_browser_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;30;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[fullscreen_view_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/fullscreen_view_interaction_test.exe")
set_tests_properties([=[fullscreen_view_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;34;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[main_window_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/main_window_interaction_test.exe")
set_tests_properties([=[main_window_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;38;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[curves_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/curves_dialog_interaction_test.exe")
set_tests_properties([=[curves_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;42;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[postprocess_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/postprocess_dialog_interaction_test.exe")
set_tests_properties([=[postprocess_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;46;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[xaos_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/xaos_dialog_interaction_test.exe")
set_tests_properties([=[xaos_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;50;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[force_symmetry_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/force_symmetry_dialog_interaction_test.exe")
set_tests_properties([=[force_symmetry_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;54;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[transform_panel_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/transform_panel_interaction_test.exe")
set_tests_properties([=[transform_panel_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;58;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[preview_label_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/preview_label_interaction_test.exe")
set_tests_properties([=[preview_label_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;62;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[render_all_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/render_all_dialog_interaction_test.exe")
set_tests_properties([=[render_all_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;66;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[smooth_palette_dialog_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/smooth_palette_dialog_interaction_test.exe")
set_tests_properties([=[smooth_palette_dialog_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;70;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[memory_budget_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/memory_budget_test.exe")
set_tests_properties([=[memory_budget_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;74;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[editor_window_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/editor_window_interaction_test.exe")
set_tests_properties([=[editor_window_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;78;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[window_geometry_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/window_geometry_test.exe")
set_tests_properties([=[window_geometry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;82;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[adjust_panel_interaction_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/adjust_panel_interaction_test.exe")
set_tests_properties([=[adjust_panel_interaction_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;86;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
add_test([=[editor_window_adjust_panel_test]=] "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/build-release/tests/ui/editor_window_adjust_panel_test.exe")
set_tests_properties([=[editor_window_adjust_panel_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;90;add_test;C:/Users/andre/Documents/Code/apop_patched/apophysis-cpp/tests/ui/CMakeLists.txt;0;")
